---
name: Travis  
surname: Gerke, ScD
position: "epidemiologist • data scientist • statistician"
address: "H. Lee Moffitt Cancer Center & Research Institute, 12902 Magnolia Drive, Tampa, FL 33612"
phone: +1 813 745 6448
www: travisgerke.com
email: "travis.gerke@moffitt.org"
twitter: travisgerke
github: tgerke
linkedin: travisgerke
headcolor: 00589A
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Summary

Text here.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Doctor of Science (ScD), Epidemiology", "2014", "Harvard School of Public Health", "Boston, MA",
  "Master of Arts (AM), Biostatistics", "2011", "Harvard University", "Cambridge, MA",
  "Bachelor of Science (BS), Statistics", "2009", "University of Florida", "Gainesville, FL"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

\vspace{-.7cm}
```{r}
tribble(
  ~ Degree, ~ Year,
  "Bachelor of Arts (BA), Mathematics", "2009"
) %>% 
  detailed_entries(Degree, Year)
```

# Experience

 * Thing 1
 * Thing 2
 * Thing 3

# Impact

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

<!--
# Publications

```{r}
scholar::get_publications("mP-fw2gAAAAJ&") %>% 
  filter(cites > 30) %>% 
  distinct(title, .keep_all = TRUE) %>%
  transmute(bibtype = "Article", author = as.character(author),
            title = as.character(title),
            journaltitle = as.character(journal), year, key = row_number()) %>% 
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("gerke.bib")

bibliography_entries("gerke.bib")
```
-->
